# Generated by Django 5.1.2 on 2024-10-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordInfo',
            fields=[
                ('person_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=36, null=True)),
                ('person_card_no', models.CharField(blank=True, max_length=20, null=True)),
                ('attendance_date_time', models.BigIntegerField()),
                ('attendance_state', models.IntegerField()),
                ('attendance_method', models.IntegerField()),
                ('device_ip_address', models.CharField(blank=True, max_length=20, null=True)),
                ('device_name', models.CharField(blank=True, max_length=50, null=True)),
                ('snapshots_path', models.CharField(blank=True, default='', max_length=200)),
                ('handler', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_utc_time', models.BigIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendancerecordinfo',
                'unique_together': {('person_id', 'attendance_date_time')},
            },
        ),
    ]
